spring:
  application:
    name: shopbox

  config:
    import: optional:file:.env.${spring.profiles.active}[.properties]

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${SHOPBOX_DB_NAME}?serverTimezone=${SERVER_TIME_ZONE}&characterEncoding=${CHARACTER_ENCODING}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

outbox:
  relay:
    interval: 5000 # ms

order:
  lock-strategy: ${ORDER_LOCK_STRATEGY:optimistic}

inventory:
  lock-strategy: ${INVENTORY_LOCK_STRATEGY:optimistic}
